name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      continue-on-error: true

    - name: Upload Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: validacion-manual-reporte
        path: playwright-report/
        retention-days: 7